### ISSUE TITLE
CS:GO performance tracking across game sessions

### ISSUE THREAD

**Issue by Tajmoti** [chalankolachtanovity/Bot_ready#18]
I'd like to have a webpage where it would be possible to see how each player is doing over time.

- These statistics would be sampled before the start of a session and after the session ends. When the session ends, each player's performance would be calculated and saved into persistent storage (a database).
- Results of each session should be accessible on the webpage and it should be possible to check the difference in each stat (weapon kills, headshots, k/d,...) from before and after the session.
- Improvements across sessions should be plotted on an interactive graph.
- It should be possible to choose which stats should be visible on the graph and also mix them if it makes sense (e.g. AK-47 and M4A1 kills can be shown on the same graph if the user wants, but mixing K/D and AK-47 kills doesn't make sense).

### TODO
- [x] Capture session stats before session start and after session end
- [x] Calculate difference in each stat before session start and after session end
- [x] Save it all into a database
- [x] Create a **Session history** webpage with a list of all sessions. Each session should be clickable and lead to **Session details**.
- [x] Create a **Session details** webpage with the possibility to see difference in each stat for each player. UI should be nice, it should have some tabs e.g. by stat categories (weapon kills, k/d, total kills/deaths,...) and probably a dropdown to switch between players
- [x] Create a ***Performance chart*** webpage with the possibilty to choose which stat to track for which player over time and plot it all on a graph

**Comment by chalankolachtanovity** [comment]
It's all done
