### ISSUE TITLE
Introduce versioning

### ISSUE THREAD

**Issue by Tajmoti** [chalankolachtanovity/Bot_ready#4]
To keep track of future changes and improvements, a versioning scheme should be introduced. I'd suggest semantic versioning and tagging each release and creating a GitHub release. See these pages for best practices.

[Semantic Versioning](https://semver.org/)
[Keep a Changelog](https://keepachangelog.com/en/1.0.0/)

### Tasks
- [x] Introduce semantic versioning
- [x] Create a CHANGELOG.md file and update it with each change
- [x] Publish all releases on GitHub
