### ISSUE TITLE
Code quality improvements

### ISSUE THREAD

**Issue by Tajmoti** [chalankolachtanovity/Bot_ready#5]
The code is very explicit and common parts could be extracted to increase clarity. For example, if-else chains could be replaced with lists of strings and lists of command handlers.

### Tasks

- [x] Replace if-elif-else chain of messages with a top-level list of strings
- [x] Extract command handling behaviour into a list of handlers or at least into separate functions to de-clutter the `on_message` function
- [x] Make code conformant to PEP8 - use flake8 and/or PyLint
- [x] Maybe add type annotations
- [x] Try to get rid of the global `ready` variable (for example using classes - see discord library documentation)

**Comment by chalankolachtanovity** [comment]
Done.
